logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10000MB}
      max-request-size: ${MAX_REQUEST_SIZE:10000MB}
  messages:
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:validate}
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
    show-sql: false
  mail: #TODO: change this values with the correct ones from your project
    enabled: ${MAIL_ENABLED:false}
    from: ${MAIL_FROM:example@example.com}
    host: ${MAIL_HOST:smtp.gmail.com}
    password: ${MAIL_PASSWORD:slmr qmbd qohv zixv}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:example@example.com}
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    password: ${DB_PASSWORD:135790}
    username: ${DB_USERNAME:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/restaurante}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: ${MIGRATIONS_ENABLED:true}
    locations: classpath:db.migration
    url: ${DB_URL:jdbc:postgresql://localhost:5432/restaurante}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:135790}
server:
  port:
    ${PORT:8080}
default-project:
  images-public-base-folder: ${IMAGES_SRC:storage/public}
  base-url: ${BASE_URL:http://localhost:8080/api/v1}
  jwt:
    secret: ${JWT_SECRET:defaultProject2024}
    expiration: ${JWT_EXPIRATION:3000}
    issuer: ${JWT_ISSUER:Default Project API}